version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: furotama2
    ports:
      - "4306:3306"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/furotama2
      - gem_data:/usr/local/bundle
      - "$SSH_AUTH_SOCK_APP:/tmp/ssh-agent.sock"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      SSH_AUTH_SOCK: "/tmp/ssh-agent.sock"

volumes:
  gem_data:
